# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170316_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Workshop',
        ),
    ]
