# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170316_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Organizer'),
        ),
    ]
