# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170316_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='author',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='text',
        ),
        migrations.AddField(
            model_name='workshop',
            name='contact_email',
            field=models.EmailField(default=b'', max_length=75),
        ),
        migrations.AddField(
            model_name='workshop',
            name='contact_phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='desc',
            field=models.TextField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='workshop',
            name='registration_limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(default=b'', max_length=60),
        ),
    ]
