# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170316_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='contact_email',
            field=models.EmailField(default=b'', max_length=75, null=True),
        ),
    ]
