# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170316_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_age',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='price_is_for',
            field=models.CharField(blank=True, default=b'', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='url_information',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
