# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='registration_limit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
