# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170318_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='url_logo',
            field=models.URLField(default=b'', max_length=1000),
        ),
    ]
