# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_organizer_url_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(default=b'', max_length=48),
        ),
    ]
