# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170319_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='desc',
            field=models.TextField(default=b'', max_length=195),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(default=b'', max_length=44),
        ),
    ]
