# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170319_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='desc',
            field=models.TextField(default=b'', max_length=185),
        ),
    ]
